# Generated by Django 4.2.3 on 2023-07-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_rename_max_leadas_plan_max_leads_team_plan'),
        ('team', '0004_auto_20230708_2109'),
    ]

    operations = [
    ]
